server:
  port: 80
spring:
  application:
    name: sugar_music
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${DATABASE_NAME}?characterEncoding=UTF8&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}